# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master

resources:
- repo: self

variables:
  - group: acrDetails
  - name: dockerRegistryServiceConnection
    value: 'Sedgwick-dockerhub'
  - name: imageRepository
    value: 'webgoat-8.0'
  - name: dockerfilePath
    value: 'webgoat-server/Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'
  - name: resourceGroup
    value: 'rg-lab-projects-eastus'
  - name: acrRegistry
    value: 'registry.hub.docker.com'
  - name: subscriptionConnection
    value: 'Visual Studio Enterprise(d7106f86-a4e9-40ec-83d3-08b03cb7bcbf)'
  - name: containerGroup
    value: 'Webgoat-Container-Group'
  - name: containerDNS
    value: 'Atlanta-Webgoat-POC'

# build steps to build and push WebGoat container to ACR
stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: Maven@1
      displayName: Maven
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        mavenVersionOption: 'Default'

    - task: Docker@2
      displayName: Build and push an WebGoat image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
# deploying to development stage
- stage: DeployToDev
  displayName: Deploy to Dev stage
  dependsOn: Build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/'))
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      vmImage: 'ubuntu-latest'

    environment: 'WebGoat-Dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@1
              displayName: Deploy to WebGoat container Dev ACI
              inputs:
                azureSubscription: $(subscriptionConnection)
                scriptLocation: 'inlineScript'
                inlineScript: 'az container create --resource-group $(resourceGroup) --name $(containerGroup) --image $(acrRegistry)/$(imageRepository):$(tag) --dns-name-label $(containerDNS) --ports 8080 --registry-username $(acrUsername) --r